extend type Query {
    auditLogs(
        store_id: ID!,
        page: Int,
        per_page: Int,
        start_date: String,
        end_date: String,
        object_type: String,
        action: String,
        search: String
    ): AuditLogPage!
        @guard(with: ["sanctum"])
        @field(resolver: "App\\GraphQL\\Queries\\AuditLogResolver@index")

    businessAuditLogs(
        business_id: ID!,
        page: Int,
        per_page: Int,
        start_date: String,
        end_date: String,
        object_type: String,
        action: String,
        store_name: String,
        search: String
    ): AuditLogPage!
        @guard(with: ["sanctum"])
        @field(resolver: "App\\GraphQL\\Queries\\AuditLogResolver@business")
}
