extend type Query {
    banks(business_id: ID!, include_inactive: Boolean): [Bank!]!
        @guard(with: ["sanctum"])
        @field(resolver: "App\\GraphQL\\Queries\\BankResolver@all")

    bank(id: ID!): Bank
        @guard(with: ["sanctum"])
        @field(resolver: "App\\GraphQL\\Queries\\BankResolver@findById")

    searchBanks(business_id: ID!, q: String!, include_inactive: Boolean, limit: Int): [Bank!]!
        @guard(with: ["sanctum"])
        @field(resolver: "App\\GraphQL\\Queries\\BankResolver@search")
}
