extend type Mutation {
    createProduct(store_id: ID!, input: CreateProductInput! @spread): Product!
        @guard(with: ["sanctum"])
        @field(resolver: "App\\GraphQL\\Mutations\\ProductResolver@create")

    updateProduct(id: ID!, input: UpdateProductInput! @spread): Product!
        @guard(with: ["sanctum"])
        @field(resolver: "App\\GraphQL\\Mutations\\ProductResolver@update")

    deleteProduct(id: ID!): Boolean!
        @guard(with: ["sanctum"])
        @field(resolver: "App\\GraphQL\\Mutations\\ProductResolver@delete")
}

input CreateProductInput {
    name: String! @rules(apply: ["required", "string", "min:1", "max:100"])
    product_category_id: ID! @rules(apply: ["required", "integer"])
    unit_id: ID! @rules(apply: ["required", "integer"])
}

input UpdateProductInput {
    name: String @rules(apply: ["sometimes", "string", "min:1", "max:100"])
    product_category_id: ID @rules(apply: ["sometimes", "integer"])
    unit_id: ID @rules(apply: ["sometimes", "integer"])
    is_active: Boolean @rules(apply: ["sometimes", "boolean"])
}
