export const ErrorCode = {
    // Auth
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
    SESSION_EXPIRED: 'SESSION_EXPIRED',
    INVALID_CODE: 'INVALID_CODE',
    CODE_EXPIRED: 'CODE_EXPIRED',
    PASSWORDS_NOT_MATCH: 'PASSWORDS_NOT_MATCH',
    OLD_PASSWORD_INCORRECT: 'OLD_PASSWORD_INCORRECT',
    REGISTRATION_EXPIRED: 'REGISTRATION_EXPIRED',
    PASSWORD_SAME_AS_CURRENT: 'PASSWORD_SAME_AS_CURRENT',
    RESET_CODE_LOCKED: 'RESET_CODE_LOCKED',

    // Authorization
    FORBIDDEN: 'FORBIDDEN',

    // Business
    BUSINESS_NOT_FOUND: 'BUSINESS_NOT_FOUND',
    TAX_CODE_TAKEN: 'TAX_CODE_TAKEN',

    // Store
    STORE_NOT_FOUND: 'STORE_NOT_FOUND',

    // Supplier
    SUPPLIER_NOT_FOUND: 'SUPPLIER_NOT_FOUND',
    SUPPLIER_NAME_TAKEN: 'SUPPLIER_NAME_TAKEN',
    SUPPLIER_IN_USE: 'SUPPLIER_IN_USE',

    // Customer
    CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',
    CUSTOMER_PHONE_TAKEN: 'CUSTOMER_PHONE_TAKEN',
    CUSTOMER_IN_USE: 'CUSTOMER_IN_USE',

    // Bank
    BANK_NOT_FOUND: 'BANK_NOT_FOUND',
    BANK_NAME_TAKEN: 'BANK_NAME_TAKEN',
    BANK_IN_USE: 'BANK_IN_USE',
    BANK_INACTIVE: 'BANK_INACTIVE',

    // Bank account
    BANK_ACCOUNT_NOT_FOUND: 'BANK_ACCOUNT_NOT_FOUND',
    BANK_ACCOUNT_NUMBER_TAKEN: 'BANK_ACCOUNT_NUMBER_TAKEN',

    // Unit
    UNIT_NOT_FOUND: 'UNIT_NOT_FOUND',
    UNIT_NAME_TAKEN: 'UNIT_NAME_TAKEN',
    UNIT_IN_USE: 'UNIT_IN_USE',
    UNIT_INACTIVE: 'UNIT_INACTIVE',

    // Product
    PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
    PRODUCT_NAME_TAKEN: 'PRODUCT_NAME_TAKEN',
    PRODUCT_IN_USE: 'PRODUCT_IN_USE',
    PRODUCT_INACTIVE: 'PRODUCT_INACTIVE',

    // Product category
    PRODUCT_CATEGORY_NOT_FOUND: 'PRODUCT_CATEGORY_NOT_FOUND',
    PRODUCT_CATEGORY_NAME_TAKEN: 'PRODUCT_CATEGORY_NAME_TAKEN',
    PRODUCT_CATEGORY_CODE_TAKEN: 'PRODUCT_CATEGORY_CODE_TAKEN',
    PRODUCT_CATEGORY_IN_USE: 'PRODUCT_CATEGORY_IN_USE',
    PRODUCT_CATEGORY_INACTIVE: 'PRODUCT_CATEGORY_INACTIVE',
    PRODUCT_CATEGORY_CODE_IMMUTABLE: 'PRODUCT_CATEGORY_CODE_IMMUTABLE',
    PRODUCT_CATEGORY_SYSTEM_LOCKED: 'PRODUCT_CATEGORY_SYSTEM_LOCKED',

    // Tag
    TAG_NOT_FOUND: 'TAG_NOT_FOUND',
    TAG_NAME_TAKEN: 'TAG_NAME_TAKEN',
    TAG_VALUE_NOT_FOUND: 'TAG_VALUE_NOT_FOUND',
    TAG_VALUE_TAKEN: 'TAG_VALUE_TAKEN',
    TAG_VALUE_INVALID: 'TAG_VALUE_INVALID',

    // Invoice extraction (AI)
    EXTRACTION_INVALID_FILE: 'EXTRACTION_INVALID_FILE',
    EXTRACTION_EMPTY: 'EXTRACTION_EMPTY',
    EXTRACTION_UNCONFIGURED: 'EXTRACTION_UNCONFIGURED',
    EXTRACTION_FAILED: 'EXTRACTION_FAILED',
    EXTRACTION_NEEDS_AI: 'EXTRACTION_NEEDS_AI',

    // Province
    PROVINCE_NOT_FOUND: 'PROVINCE_NOT_FOUND',

    CANNOT_CHANGE_OWNER_ROLE: 'CANNOT_CHANGE_OWNER_ROLE',
    CANNOT_REMOVE_OWNER: 'CANNOT_REMOVE_OWNER',

    // Invitation
    INVITATION_NOT_FOUND: 'INVITATION_NOT_FOUND',
    INVITATION_EXPIRED: 'INVITATION_EXPIRED',
    INVITATION_ALREADY_ACCEPTED: 'INVITATION_ALREADY_ACCEPTED',
    INVITATION_ALREADY_MEMBER: 'INVITATION_ALREADY_MEMBER',
    INVITATION_PENDING_EXISTS: 'INVITATION_PENDING_EXISTS',
    INVITATION_CANNOT_INVITE_SELF: 'INVITATION_CANNOT_INVITE_SELF',
    INVITATION_WRONG_EMAIL: 'INVITATION_WRONG_EMAIL',
    INVITATION_CANNOT_INVITE_OWNER: 'INVITATION_CANNOT_INVITE_OWNER',
    INVITATION_NOT_CANCELLABLE: 'INVITATION_NOT_CANCELLABLE',

    // General
    RESOURCE_IN_USE: 'RESOURCE_IN_USE',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    NOT_FOUND: 'NOT_FOUND',
    SERVER_ERROR: 'SERVER_ERROR',
    NETWORK_ERROR: 'NETWORK_ERROR',
    RATE_LIMITED: 'RATE_LIMITED',
}