export const ErrorCode = {
    // Auth
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
    SESSION_EXPIRED: 'SESSION_EXPIRED',
    INVALID_CODE: 'INVALID_CODE',
    CODE_EXPIRED: 'CODE_EXPIRED',
    PASSWORDS_NOT_MATCH: 'PASSWORDS_NOT_MATCH',
    OLD_PASSWORD_INCORRECT: 'OLD_PASSWORD_INCORRECT',
    REGISTRATION_EXPIRED: 'REGISTRATION_EXPIRED',

    // Authorization
    FORBIDDEN: 'FORBIDDEN',

    // Business
    BUSINESS_NOT_FOUND: 'BUSINESS_NOT_FOUND',
    TAX_CODE_TAKEN: 'TAX_CODE_TAKEN',

    // Store
    STORE_NOT_FOUND: 'STORE_NOT_FOUND',
    CANNOT_CHANGE_OWNER_ROLE: 'CANNOT_CHANGE_OWNER_ROLE',
    CANNOT_REMOVE_OWNER: 'CANNOT_REMOVE_OWNER',

    // General
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    NOT_FOUND: 'NOT_FOUND',
    SERVER_ERROR: 'SERVER_ERROR',
    NETWORK_ERROR: 'NETWORK_ERROR',
    RATE_LIMITED: 'RATE_LIMITED',
}