export const ErrorCode = {
    // Auth
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
    SESSION_EXPIRED: 'SESSION_EXPIRED',
    INVALID_CODE: 'INVALID_CODE',
    CODE_EXPIRED: 'CODE_EXPIRED',
    PASSWORDS_NOT_MATCH: 'PASSWORDS_NOT_MATCH',
    OLD_PASSWORD_INCORRECT: 'OLD_PASSWORD_INCORRECT',
    REGISTRATION_EXPIRED: 'REGISTRATION_EXPIRED',

    // Authorization
    FORBIDDEN: 'FORBIDDEN',

    // Business
    BUSINESS_NOT_FOUND: 'BUSINESS_NOT_FOUND',
    TAX_CODE_TAKEN: 'TAX_CODE_TAKEN',

    // Store
    STORE_NOT_FOUND: 'STORE_NOT_FOUND',

    // Supplier
    SUPPLIER_NOT_FOUND: 'SUPPLIER_NOT_FOUND',
    CANNOT_CHANGE_OWNER_ROLE: 'CANNOT_CHANGE_OWNER_ROLE',
    CANNOT_REMOVE_OWNER: 'CANNOT_REMOVE_OWNER',

    // Invitation
    INVITATION_NOT_FOUND: 'INVITATION_NOT_FOUND',
    INVITATION_EXPIRED: 'INVITATION_EXPIRED',
    INVITATION_ALREADY_ACCEPTED: 'INVITATION_ALREADY_ACCEPTED',
    INVITATION_ALREADY_MEMBER: 'INVITATION_ALREADY_MEMBER',
    INVITATION_PENDING_EXISTS: 'INVITATION_PENDING_EXISTS',
    INVITATION_CANNOT_INVITE_SELF: 'INVITATION_CANNOT_INVITE_SELF',
    INVITATION_WRONG_EMAIL: 'INVITATION_WRONG_EMAIL',
    INVITATION_CANNOT_INVITE_OWNER: 'INVITATION_CANNOT_INVITE_OWNER',
    INVITATION_NOT_CANCELLABLE: 'INVITATION_NOT_CANCELLABLE',

    // General
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    NOT_FOUND: 'NOT_FOUND',
    SERVER_ERROR: 'SERVER_ERROR',
    NETWORK_ERROR: 'NETWORK_ERROR',
    RATE_LIMITED: 'RATE_LIMITED',
}