<?php

namespace App\Enums;

enum ErrorCode: string
{
    // Auth
    case INVALID_CREDENTIALS = 'INVALID_CREDENTIALS';
    case ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND';
    case SESSION_EXPIRED = 'SESSION_EXPIRED';
    case INVALID_CODE = 'INVALID_CODE';
    case CODE_EXPIRED = 'CODE_EXPIRED';
    case PASSWORDS_NOT_MATCH = 'PASSWORDS_NOT_MATCH';
    case OLD_PASSWORD_INCORRECT = 'OLD_PASSWORD_INCORRECT';
    case REGISTRATION_EXPIRED = 'REGISTRATION_EXPIRED';

    // Authorization
    case FORBIDDEN = 'FORBIDDEN';

    // Business
    case BUSINESS_NOT_FOUND = 'BUSINESS_NOT_FOUND';
    case TAX_CODE_TAKEN = 'TAX_CODE_TAKEN';

    // Store
    case STORE_NOT_FOUND = 'STORE_NOT_FOUND';
    case CANNOT_CHANGE_OWNER_ROLE = 'CANNOT_CHANGE_OWNER_ROLE';
    case CANNOT_REMOVE_OWNER = 'CANNOT_REMOVE_OWNER';

    // Supplier
    case SUPPLIER_NOT_FOUND = 'SUPPLIER_NOT_FOUND';
    case SUPPLIER_NAME_TAKEN = 'SUPPLIER_NAME_TAKEN';

    // Customer
    case CUSTOMER_NOT_FOUND = 'CUSTOMER_NOT_FOUND';
    case CUSTOMER_PHONE_TAKEN = 'CUSTOMER_PHONE_TAKEN';

    // Bank
    case BANK_NOT_FOUND = 'BANK_NOT_FOUND';
    case BANK_NAME_TAKEN = 'BANK_NAME_TAKEN';
    case BANK_IN_USE = 'BANK_IN_USE';
    case BANK_INACTIVE = 'BANK_INACTIVE';

    // Bank account
    case BANK_ACCOUNT_NOT_FOUND = 'BANK_ACCOUNT_NOT_FOUND';
    case BANK_ACCOUNT_NUMBER_TAKEN = 'BANK_ACCOUNT_NUMBER_TAKEN';

    // Unit
    case UNIT_NOT_FOUND = 'UNIT_NOT_FOUND';
    case UNIT_NAME_TAKEN = 'UNIT_NAME_TAKEN';
    case UNIT_IN_USE = 'UNIT_IN_USE';
    case UNIT_INACTIVE = 'UNIT_INACTIVE';

    // Product
    case PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND';
    case PRODUCT_NAME_TAKEN = 'PRODUCT_NAME_TAKEN';
    case PRODUCT_IN_USE = 'PRODUCT_IN_USE';
    case PRODUCT_INACTIVE = 'PRODUCT_INACTIVE';

    // Product category
    case PRODUCT_CATEGORY_NOT_FOUND = 'PRODUCT_CATEGORY_NOT_FOUND';
    case PRODUCT_CATEGORY_NAME_TAKEN = 'PRODUCT_CATEGORY_NAME_TAKEN';
    case PRODUCT_CATEGORY_CODE_TAKEN = 'PRODUCT_CATEGORY_CODE_TAKEN';
    case PRODUCT_CATEGORY_IN_USE = 'PRODUCT_CATEGORY_IN_USE';
    case PRODUCT_CATEGORY_INACTIVE = 'PRODUCT_CATEGORY_INACTIVE';
    case PRODUCT_CATEGORY_CODE_IMMUTABLE = 'PRODUCT_CATEGORY_CODE_IMMUTABLE';
    case PRODUCT_CATEGORY_SYSTEM_LOCKED = 'PRODUCT_CATEGORY_SYSTEM_LOCKED';

    // Tag
    case TAG_NOT_FOUND = 'TAG_NOT_FOUND';
    case TAG_NAME_TAKEN = 'TAG_NAME_TAKEN';
    case TAG_VALUE_NOT_FOUND = 'TAG_VALUE_NOT_FOUND';
    case TAG_VALUE_TAKEN = 'TAG_VALUE_TAKEN';
    case TAG_VALUE_INVALID = 'TAG_VALUE_INVALID';

    // Tax
    case TAX_NOT_FOUND = 'TAX_NOT_FOUND';
    case TAX_NAME_TAKEN = 'TAX_NAME_TAKEN';
    case TAX_SYSTEM_LOCKED = 'TAX_SYSTEM_LOCKED';

    // Invoice
    case INVOICE_NOT_FOUND = 'INVOICE_NOT_FOUND';
    case INVOICE_PARTY_INVALID = 'INVOICE_PARTY_INVALID';
    case INVOICE_PRODUCT_INVALID = 'INVOICE_PRODUCT_INVALID';
    case INVOICE_NO_ITEMS = 'INVOICE_NO_ITEMS';
    case INVOICE_IMMUTABLE = 'INVOICE_IMMUTABLE';
    case INSUFFICIENT_STOCK = 'INSUFFICIENT_STOCK';
    case INVOICE_STOCK_CONSUMED = 'INVOICE_STOCK_CONSUMED';

    // Province
    case PROVINCE_NOT_FOUND = 'PROVINCE_NOT_FOUND';

    // Export
    case EXPORT_NOT_FOUND = 'EXPORT_NOT_FOUND';
    case EXPORT_NOT_READY = 'EXPORT_NOT_READY';
    case EXPORT_FILE_MISSING = 'EXPORT_FILE_MISSING';

    // Invitation
    case INVITATION_NOT_FOUND = 'INVITATION_NOT_FOUND';
    case INVITATION_EXPIRED = 'INVITATION_EXPIRED';
    case INVITATION_ALREADY_ACCEPTED = 'INVITATION_ALREADY_ACCEPTED';
    case INVITATION_ALREADY_MEMBER = 'INVITATION_ALREADY_MEMBER';
    case INVITATION_PENDING_EXISTS = 'INVITATION_PENDING_EXISTS';
    case INVITATION_CANNOT_INVITE_SELF = 'INVITATION_CANNOT_INVITE_SELF';
    case INVITATION_WRONG_EMAIL = 'INVITATION_WRONG_EMAIL';
    case INVITATION_CANNOT_INVITE_OWNER = 'INVITATION_CANNOT_INVITE_OWNER';
    case INVITATION_NOT_CANCELLABLE = 'INVITATION_NOT_CANCELLABLE';
    case INVITATION_INVALID = 'INVITATION_INVALID';

    // General
    case VALIDATION_ERROR = 'VALIDATION_ERROR';
    case NOT_FOUND = 'NOT_FOUND';
    case SERVER_ERROR = 'SERVER_ERROR';
    case NETWORK_ERROR = 'NETWORK_ERROR';
    case RATE_LIMITED = 'RATE_LIMITED';

    public function statusCode(): int
    {
        return match ($this) {
            self::INVALID_CREDENTIALS,
            self::INVALID_CODE,
            self::PASSWORDS_NOT_MATCH,
            self::OLD_PASSWORD_INCORRECT,
            self::CODE_EXPIRED,
            self::REGISTRATION_EXPIRED,
            self::TAX_CODE_TAKEN,
            self::SUPPLIER_NAME_TAKEN,
            self::CUSTOMER_PHONE_TAKEN,
            self::BANK_NAME_TAKEN,
            self::BANK_IN_USE,
            self::BANK_INACTIVE,
            self::BANK_ACCOUNT_NUMBER_TAKEN,
            self::UNIT_NAME_TAKEN,
            self::UNIT_IN_USE,
            self::UNIT_INACTIVE,
            self::PRODUCT_NAME_TAKEN,
            self::PRODUCT_IN_USE,
            self::PRODUCT_INACTIVE,
            self::PRODUCT_CATEGORY_NAME_TAKEN,
            self::PRODUCT_CATEGORY_CODE_TAKEN,
            self::PRODUCT_CATEGORY_IN_USE,
            self::PRODUCT_CATEGORY_INACTIVE,
            self::PRODUCT_CATEGORY_CODE_IMMUTABLE,
            self::PRODUCT_CATEGORY_SYSTEM_LOCKED,
            self::TAG_NAME_TAKEN,
            self::TAG_VALUE_TAKEN,
            self::TAG_VALUE_INVALID,
            self::TAX_NAME_TAKEN,
            self::TAX_SYSTEM_LOCKED,
            self::INVOICE_PARTY_INVALID,
            self::INVOICE_PRODUCT_INVALID,
            self::INVOICE_NO_ITEMS,
            self::INVOICE_IMMUTABLE,
            self::INSUFFICIENT_STOCK,
            self::INVOICE_STOCK_CONSUMED,
            self::CANNOT_CHANGE_OWNER_ROLE,
            self::CANNOT_REMOVE_OWNER,
            self::INVITATION_EXPIRED,
            self::INVITATION_ALREADY_ACCEPTED,
            self::INVITATION_ALREADY_MEMBER,
            self::INVITATION_PENDING_EXISTS,
            self::INVITATION_CANNOT_INVITE_SELF,
            self::INVITATION_WRONG_EMAIL,
            self::INVITATION_CANNOT_INVITE_OWNER,
            self::INVITATION_NOT_CANCELLABLE,
            self::EXPORT_NOT_READY,
            self::VALIDATION_ERROR => 400,

            self::SESSION_EXPIRED => 401,

            self::FORBIDDEN => 403,

            self::ACCOUNT_NOT_FOUND,
            self::BUSINESS_NOT_FOUND,
            self::STORE_NOT_FOUND,
            self::SUPPLIER_NOT_FOUND,
            self::CUSTOMER_NOT_FOUND,
            self::BANK_NOT_FOUND,
            self::BANK_ACCOUNT_NOT_FOUND,
            self::UNIT_NOT_FOUND,
            self::PRODUCT_NOT_FOUND,
            self::PRODUCT_CATEGORY_NOT_FOUND,
            self::TAG_NOT_FOUND,
            self::TAG_VALUE_NOT_FOUND,
            self::TAX_NOT_FOUND,
            self::INVOICE_NOT_FOUND,
            self::PROVINCE_NOT_FOUND,
            self::INVITATION_NOT_FOUND,
            self::EXPORT_NOT_FOUND,
            self::EXPORT_FILE_MISSING,
            self::NOT_FOUND => 404,

            self::RATE_LIMITED => 429,

            self::SERVER_ERROR,
            self::NETWORK_ERROR => 500,
        };
    }
}
