<?php

namespace App\Enums;

enum ErrorCode: string
{
    // Auth
    case INVALID_CREDENTIALS = 'INVALID_CREDENTIALS';
    case ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND';
    case SESSION_EXPIRED = 'SESSION_EXPIRED';
    case INVALID_CODE = 'INVALID_CODE';
    case CODE_EXPIRED = 'CODE_EXPIRED';
    case PASSWORDS_NOT_MATCH = 'PASSWORDS_NOT_MATCH';
    case OLD_PASSWORD_INCORRECT = 'OLD_PASSWORD_INCORRECT';
    case REGISTRATION_EXPIRED = 'REGISTRATION_EXPIRED';

    // Authorization
    case FORBIDDEN = 'FORBIDDEN';

    // Business
    case BUSINESS_NOT_FOUND = 'BUSINESS_NOT_FOUND';
    case TAX_CODE_TAKEN = 'TAX_CODE_TAKEN';

    // Store
    case STORE_NOT_FOUND = 'STORE_NOT_FOUND';
    case CANNOT_CHANGE_OWNER_ROLE = 'CANNOT_CHANGE_OWNER_ROLE';
    case CANNOT_REMOVE_OWNER = 'CANNOT_REMOVE_OWNER';

    // Invitation
    case INVITATION_NOT_FOUND = 'INVITATION_NOT_FOUND';
    case INVITATION_EXPIRED = 'INVITATION_EXPIRED';
    case INVITATION_ALREADY_ACCEPTED = 'INVITATION_ALREADY_ACCEPTED';
    case INVITATION_ALREADY_MEMBER = 'INVITATION_ALREADY_MEMBER';
    case INVITATION_PENDING_EXISTS = 'INVITATION_PENDING_EXISTS';
    case INVITATION_CANNOT_INVITE_SELF = 'INVITATION_CANNOT_INVITE_SELF';
    case INVITATION_WRONG_EMAIL = 'INVITATION_WRONG_EMAIL';
    case INVITATION_CANNOT_INVITE_OWNER = 'INVITATION_CANNOT_INVITE_OWNER';
    case INVITATION_NOT_CANCELLABLE = 'INVITATION_NOT_CANCELLABLE';
    case INVITATION_INVALID = 'INVITATION_INVALID';

    // General
    case VALIDATION_ERROR = 'VALIDATION_ERROR';
    case NOT_FOUND = 'NOT_FOUND';
    case SERVER_ERROR = 'SERVER_ERROR';
    case NETWORK_ERROR = 'NETWORK_ERROR';
    case RATE_LIMITED = 'RATE_LIMITED';

    public function statusCode(): int
    {
        return match ($this) {
            self::INVALID_CREDENTIALS,
            self::INVALID_CODE,
            self::PASSWORDS_NOT_MATCH,
            self::OLD_PASSWORD_INCORRECT,
            self::CODE_EXPIRED,
            self::REGISTRATION_EXPIRED,
            self::TAX_CODE_TAKEN,
            self::CANNOT_CHANGE_OWNER_ROLE,
            self::CANNOT_REMOVE_OWNER,
            self::INVITATION_EXPIRED,
            self::INVITATION_ALREADY_ACCEPTED,
            self::INVITATION_ALREADY_MEMBER,
            self::INVITATION_PENDING_EXISTS,
            self::INVITATION_CANNOT_INVITE_SELF,
            self::INVITATION_WRONG_EMAIL,
            self::INVITATION_CANNOT_INVITE_OWNER,
            self::INVITATION_NOT_CANCELLABLE,
            self::VALIDATION_ERROR => 400,

            self::SESSION_EXPIRED => 401,

            self::FORBIDDEN => 403,

            self::ACCOUNT_NOT_FOUND,
            self::BUSINESS_NOT_FOUND,
            self::STORE_NOT_FOUND,
            self::INVITATION_NOT_FOUND,
            self::NOT_FOUND => 404,

            self::RATE_LIMITED => 429,

            self::SERVER_ERROR,
            self::NETWORK_ERROR => 500,
        };
    }
}